[book]
title = "PenaltyControlAssist - Документация"
authors = ["Avircut"]
description = "Документация для приложения PenaltyControlAssist"
language = "ru"
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/yourusername/PenaltyControlAssist"
edit-url-template = "https://github.com/yourusername/PenaltyControlAssist/edit/main/docs/{path}"

[output.html.search]
enable = true
limit-results = 20
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
